version: '3.1'

volumes:
  easyleaderboard-data:

networks:
  easyleaderboard-network:


services:

  server:
    container_name: ezlb-server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
    networks:
      - easyleaderboard-network

  mongo:
    container_name: ezlb-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - easyleaderboard-data:/data/db
    networks:
      - easyleaderboard-network

  mongo-express:
    container_name: ezlb-mongo-panel
    profiles:
      - admin-panel
    image: mongo-express
    restart: always
    ports:
      - 127.0.0.1:8081:8081/tcp
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/
    networks:
      - easyleaderboard-network